version: "3.9"
services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=1234
volumes:
  pgdata: